server {
    listen 4200;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: cualquier ruta (ej. /pedido) cae a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cacheo largo para assets con hash en el nombre
    location ~* \.(?:js|css|woff2?|png|jpe?g|webp|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
